name: bottom_loader
description: A flutter plugin to display bottom loader.
version: 0.1.2
homepage: https://github.com/akshay512/bottom_loader

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

